weights: ''
cfg: /homes/z20ning/Bureau/Yolo/yolov5/models/yolov5n_sm.yaml
data: /homes/z20ning/Bureau/Yolo/yolov5/data/smartcam.yaml
hyp: data/hyps/hyp.scratch-high.yaml
epochs: 300
batch_size: 16
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: YOLOv5
name: yolov5n_high_smallobj_scratch
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: YOLOv5/yolov5n_high_smallobj_scratch2
